image: gitlab.endian.se:4567/daniel/rectangle-packer

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: "500"
  GIT_FETCH_EXTRA_FLAGS: --tags

stages:
  - build
  - test
  - benchmark
  - upload
  - doc
  - memory

build:
  stage: build
  tags:
    - ripper-dind
  script:
    - make build
  artifacts:
    paths:
      - "dist"

test:
  stage: test
  tags:
    - ripper-dind
  script:
    # Force with -B since dist/rectangle-packer-*.tar.gz exists
    - make -B test
    # "Test installed package (not workspace)"
    - rm -rf ./rpack
    - python3 -m pip install dist/rectangle-packer-*.tar.gz
    - python3 -W default -u -m unittest discover -v test/

benchmark:
  stage: benchmark
  tags:
    - ripper-dind
  script:
    - make build
    - PYTHONPATH=. make benchmark
  artifacts:
    paths:
      - "artifacts"

upload:
  stage: upload
  image: google/cloud-sdk
  tags:
    - ripper-dind
  script:
    - echo $BUCKET_PENLECT_COM_KEY > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gsutil rsync -r artifacts gs://bucket.penlect.com/rpack

doc:
  stage: doc
  tags:
    - ripper-dind
  script:
    - make build
    - make doc
  artifacts:
    paths:
      - "doc/_build"

memory:
  stage: memory
  tags:
    - ripper-dind
  script:
    - python3 -m pip install memory-profiler==0.58.0
    - make build
    - PYTHONPATH=. mprof run python3 -m test.test_memory 300
    - mprof plot --output memory_profile.pdf
  artifacts:
    paths:
      - memory_profile.pdf

