language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
install:
  - python -m pip install -r requirements_test.txt
  - python setup.py develop
script:
  - pytest
  - pylint --rcfile test/pylint.cfg rpack